version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile_app
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
    mem_limit: 460m

  tester:
    build:
      context: .
      dockerfile: tester/Dockerfile_tester
    depends_on:
      - app
    ports:
      - "127.0.0.1:2222:22"
    environment:
      - TESTER_SSH_PASSWORD=${TESTER_SSH_PASSWORD:-changeme}
      - TEST_STAGES=${TEST_STAGES:-yapf,pylint,headers}
      - APP_URL=http://app:5000
    mem_limit: 460m